apiVersion: v1
kind: Service
metadata:
  name: model-router
spec:
  type: ClusterIP
  selector:
    app: model-router
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
